env:
  browser: true
  meteor: true
  mongo: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    modules: true
plugins:
  - react
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
