env:
  browser: true
  meteor: true
  mongo: true
  node: true
globals:
  afterEach: false
  beforeEach: false
  describe: false
  expect: false
  it: false
  jasmine: false
  pending: false
  spyOn: false
  waits: false
  waitsFor: false
  xdescribe: false
  xit: false
  jest: false
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    modules: true
plugins:
  - react
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - never
