language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: DYskv43gZ8nW618pgvrsz5iko8VIgTV0zS///mr07ShOQbQ3yLzJivwZtCMJYhVDl+h4SgveiNc7zdKkipt/PTFp5Su8FL+jIhH3pnTgWOW0HLRAj4gt1k+vsHBk7aGo07H7azw/S7uDxKFGs6DubrmYzjE1gH9nh7qJWgyZ+SpxZA+rESr4jcIihNB2yUXGGBHr0DSIne1oThfO1m/nrZfWU2P0kboBNNeL8wnwkhdTG4hWhVvI9auBy2YMsdzF0u+vqrjwgf4Y2xeEKnWjfWZPXkdZab4KDYwf1JmnJS4/ZWIjjsDnO+Ud8dy/kqv/HAEywX8zuRH1wZPrg0pIfHY4y81Cw24j2ey8GaYwopsuzi3auCLFuNDXY8AgXdai7c1xHrhmmSLZpzQdyzfEJuRB9f3i754fESj16b4i8/VMa8jlG4eikZo7DH+8bS0flmuy94biCCmuwF/sGBjfM/MsKVI/JI04GE8s20+CdX72YicuY9WdMmarSJlWNPDcXc/GmtmlXMg6e9jcyB/xGJOEroTGLQemrSVswz11iJB9r7B/J8u7LpkvVlUrCgqzwzDdkCrqcwPVCiPjCVXW1/Jwg+2aCQLY/3tLq4Gpy2jQmw9XgEZQCbPSbMg1hZRT28CE3Tk3EArEPpI0mKZtBQ3riRSWv7rT0FnHkFCPHjc=
  app: samelogic-web
