export const CREATE_SNAP = 'CREATE_SNAP'
export const CREATE_SNAP_SUCCESS = 'CREATE_SNAP_SUCCESS'
export const CREATE_SNAP_FAILURE = 'CREATE_SNAP_FAILURE'
export const RESET_NEW_SNAP = 'RESET_NEW_SNAP'

//Validate Snap fields like Emoji, Snap and Message on the server
export const VALIDATE_SNAP_FIELDS = 'VALIDATE_SNAP_FIELDS'
export const VALIDATE_SNAP_FIELDS_SUCCESS = 'VALIDATE_SNAP_FIELDS_SUCCESS'
export const VALIDATE_SNAP_FIELDS_FAILURE = 'VALIDATE_SNAP_FIELDS_FAILURE'
export const RESET_SNAP_FIELDS = 'RESET_SNAP_FIELDS'